#import <UIKit/UIKit.h>

@class SBDimmingWindow, SBUIController;

@interface SpringBoard : UIApplication
{
    SBUIController *_uiController;
    NSTimer *_menuButtonTimer;
    NSTimer *_lockButtonTimer;
    NSTimer *_idleTimer;
    NSTimer *_autoLockTimer;
    double _lastTimeIdleCausedDim;
    double _headsetButtonDownTime;
    SBDimmingWindow *_simulatedBlankingWindow;
    unsigned int _headsetButtonClickCount:8;
    unsigned int _menuButtonClickCount:8;
    unsigned int _screenshotWasTaken:1;
    unsigned int _disableAutoDimming:1;
    unsigned int _nextLockUpLocks:1;
    unsigned int _poweringDown:1;
    unsigned int _autoDimmed:1;
    unsigned int _autoDimmedToBlack:1;
    unsigned int _ipodIsPlaying:1;
    int _UIOrientation;
    NSURL *_menuDoubleTapURL;
    int _notifyDontAnimateREOToken;
    int _notifyDontAllowMediaHUDToken;
    NSString *_jetsamIncidentID;
    double _sampleSystemStartTime;
    struct __CFDictionary *_startAppsCPUTimes;
}

+ (void)printWorkspaceStacks;
+ (void)printWorkspaceLogs;

- (BOOL)registerForSystemEvents;
- (BOOL)rendersLocally;

- (void)_createLogFile;
- (void)_writeLogFile;

- (void)updatePowerlogKillingProcess:(BOOL)something;
- (void)appleIconViewRemoved;
- (void)timeZoneChanged;
- (BOOL)disableRemoteNotifications;
- (void)wipeDeviceNow;
- (void)checkForExpiredPasscode;
- (void)showLowDiskSpaceAlert;
- (void)showEDGEActivationFailureAlert:(id)fp8 reason:(id)fp12;
- (void)showWiFiAlert;
- (void)showWiFiEnterpriseTrustAlert:(id)fp8;
- (void)wifiManager:(id)fp8 scanCompleted:(id)fp12;
- (void)userDefaultsDidChange:(id)fp8;
- (void)_testPhoneAlerts;
- (void)runFieldTestScript;
- (void)_significantTimeChange;
- (void)significantTimeChange;
- (void)simulateInCallStatusBar;
- (BOOL)shouldRunFieldTestScript;
- (BOOL)supportsVictoria;
- (BOOL)iapIsInExtendedMode;
- (BOOL)_canShowNowPlayingHUD;
- (BOOL)allowMenuDoubleTap;
- (void)handleMenuDoubleTap;
- (void)_setMenuButtonTimer:(id)fp8;
- (void)_setLockButtonTimer:(id)fp8;
- (void)clearMenuButtonTimer;
- (void)_menuButtonWasHeld;
- (void)_handleMenuButtonEvent;
- (void)lockButtonWasHeld;
- (void)_powerDownNow;
- (void)_rebootNow;
- (void)reboot;
- (void)powerDown;
- (void)relaunchSpringBoard;
- (void)powerDownRequested:(id)fp8;
- (void)powerDownCanceled:(id)fp8;
- (void)_initLockButtonBearTrap;
- (void)_setLockButtonBearTrap;
- (void)_unsetLockButtonBearTrap;
- (void)_fireLockButtonBearTrap;
- (void)_sendRemoteCommand:(int)fp8 forHeadsetEvent:(GSEvent *)gsEvent;
- (void)_handleHeadsetButtonDoubleClick:(GSEvent *)gsEvent;
- (void)_handleHeadsetButtonTripleClick:(GSEvent *)gsEvent;
- (void)_handleHeadsetButtonClick:(GSEvent *)gsEvent;
- (void)smsPrefsChanged;
- (void)ALSPrefsChanged:(id)fp8;
- (void)updateCapabilitiesAndIconVisibility;
- (void)loadDebuggingAndDemoPrefs;
- (void)debuggingAndDemoPrefsWereChanged;
- (void)clockFormatChanged;
- (void)autoLockPrefsChanged;
- (void)pinPolicyChanged;
- (void)ringerChanged:(int)fp8;
- (void)showAlertForUnhandledURL:(id)fp8 error:(int)fp12;
- (void)applicationOpenURL:(id)fp8 asPanel:(BOOL)fp12 publicURLsOnly:(BOOL)fp16;
- (void)applicationOpenURL:(id)fp8 asPanel:(BOOL)fp12;
- (void)fakeVolumeButtonUpEvent:(BOOL)fp8;
- (void)fakeVolumeUpButtonUpEvent;
- (void)fakeVolumeDownButtonUpEvent;
- (void)setBacklightFactor:(NSInteger)factor;
- (void)setBacklightLevel:(CGFloat)level;
- (void)setProximitySensorEnabled:(int)fp8;
- (void)systemWillSleep;
- (void)setupMidnightTimer;
- (void)_midnightPassed;
- (void)_adjustMidnightTimerAfterSleep;
- (void)dim;
- (void)turnOffBacklight;
- (void)cancelTurnOffBacklightAfterDelay;
- (void)turnOffBacklightAfterDelay;
- (void)showSimulatedScreenBlank;
- (void)hideSimulatedScreenBlank;
- (void)dimToBlack;
- (void)undim;
- (void)lockAfterCall;
- (BOOL)shouldDimToBlackInsteadOfLock;
- (void)autoLock;
- (void)didIdle;
- (double)nextIdleTimeDuration;
- (double)nextLockTimeDuration;
- (void)clearIdleTimer;
- (void)resetIdleTimerAndUndim:(BOOL)fp8;
- (void)userEventOccurred:(id)fp8;
- (void)resetIdleTimer;
- (void)resetIdleDuration:(double)fp8;
- (void)updateRejectedInputSettings;
- (void)updateRejectedInputSettingsForInCallState:(BOOL)fp8 isOutgoing:(BOOL)fp12;
- (void)showThermalAlertIfNecessary;
- (void)respondToCurrentThermalCondition;
- (void)_beginThermalJetsamCPUSampling;
- (void)_killThermallyActiveApplication;
- (struct __CFDictionary *)_createAppsCPUTimesDictionary;
- (void)checkMemoryStatus;
- (void)_receivedMemoryNotification;
- (void)_killSpringBoardInResponseToCriticalWarning;
- (void)noteSubstantialTransitionOccured;
- (int)_frontMostAppOrientation;
- (void)noteUIOrientationChanged:(int)fp8 display:(id)fp12;
- (int)UIOrientation;
- (void)updateMenuDoubleTapSettings;
- (void)updateProximitySettings;
- (void)updateAirPortForDisplay:(id)fp8;
- (void)frontDisplayDidChange:(id)fp8;
- (void)didDismissMiniAlert;
- (void)willDisplayMiniAlert:(int *)fp8;
- (void)willDismissMiniAlert:(int *)fp8 andShowAnother:(BOOL)fp12;
- (void)setHasMiniAlerts:(BOOL)fp8;
- (BOOL)canShowAlerts;
- (BOOL)isLocked;
- (int)alertOrientation;
- (void)_tearDownNow;
- (void)tearDown;
- (BOOL)deviceIsInNowPlaying;
- (BOOL)musicIsPlaying;
- (void)setNowPlayingInfo:(id)fp8;
- (BOOL)deviceAllowsNowPlayingHUD;
- (void)setJetsamIncidentID;
- (void)clearJetsamIncidentID;
- (id)jetsamIncidentID;
- (void)clearDeviceAllowsNowPlayingHUD;

@end

