#import "UIAccelerometer+Private.h"
#import "UIAlertView+Private.h"
#import "UIApplication+Private.h"
#import "UIDevice+Private.h"
#import "UIEvent+Private.h"
#import "UIFieldEditor.h"
#import "UIHardware.h"
#import "UIKeyboard.h"
#import "UIKeyboardEmojiPage.h"
#import "UIKeyboardImpl.h"
#import "UIKeyboardInput.h"
#import "UIKeyboardLayout.h"
#import "UIKeyboardLayoutRoman.h"
#import "UIKeyDefinition.h"
#import "UINavigationItemView.h"
#import "UINavigationItemButtonView.h"
#import "UIPickerView+Private.h"
#import "UIPickerTable.h"
#import "UIResponder+Private.h"
#import "UIScroller.h"
#import "UITable.h"
#import "UITableCell.h"
#import "UITextView+Private.h"
#import "UITextViewLegacy.h"
#import "UIThreadSafeNode.h"
#import "UIWebDocumentView.h"
#import "UIWindow+Private.h"

#define TouchesPointInView()	[(UITouch *)[touches anyObject] locationInView:self]
#define TouchesPointInWindow()	[(UITouch *)[touches anyObject] locationInView:[self window]]
